### ISSUE TITLE
Decoding is not implemented yet.

### ISSUE THREAD

**Issue by JideGuru** [JacobWrenn/notus_to_html#1]
I tried decoding from `String` to `Delta` but it says `Decoding is not implemented yet.`

Please when will `Decoding` be implemented.
Thanks.

![photo_2020-05-30 14 42 22](https://user-images.githubusercontent.com/24323581/83329886-cc496900-a283-11ea-8472-6d449bbcb649.jpeg)

**Comment by JacobWrenn** [comment]
Hi @JideGuru at the moment I've only implemented encoding as I needed it for another project, which was the primary reason for making this package. I'll definitely consider adding this though. I would suggest looking at something like <https://github.com/joelcolucci/node-quill-converter> that you could run on the back-end however I'm not sure how compatible this would be with the syntax Zefyr use.

**Comment by JideGuru** [comment]
Thanks @JacobWrenn

**Comment by JacobWrenn** [comment]
Hi @JideGuru the latest version on pub.dev now has experimental support for decoding HTML. Obviously, it is limited to the capabilities of the Zefyr editor so any HTML more advanced than what markdown supports won't work. If you find any problems with it or think I've missed something then please open a new issue here.
