### ISSUE TITLE
decode html emoji not working 

### ISSUE THREAD

**Issue by mziadd** [JacobWrenn/notus_to_html#16]
`<p><span class="ql-emojiblot" data-name="sunglasses">﻿<span contenteditable="false"><span class="ap ap-sunglasses">😎</span></span>﻿</span></p>`

The above html is not working

**Comment by JacobWrenn** [comment]
Hi @mohammedX6, the HTML decoding functionality is really only intended for HTML output that was originally a notus document which therefore means only a limited set of tags and structures are supported. However, emojis themselves such as in this example `<p>😎</p>` would work.
